### ISSUE TITLE
Conflicting compiler and parser rules

### ISSUE THREAD

**Issue by drewbrokke** [metal/soyparser#2]
Soy compiler recommends using double curly braces if attribute value contains single curly braces, but soyparser does not allow double curly braces for params (or anything else?).

**Comment by drewbrokke** [comment]
Example:
```
{{param code:'YUI().use(
  \'aui-carousel\',
  function(Y) {
    // code goes here
  }
);'}}
```

**Comment by mthadley** [comment]
Thanks @drewbrokke, definitely worth looking in to.

**Comment by jbalsas** [comment]
Filed at [metal-tools-soy](https://github.com/metal/metal-tools-soy/issues/38)
