### ISSUE TITLE
Add a top-level only parse option.

### ISSUE THREAD

**Issue by mthadley** [metal/soyparser#3]
Add a top level parse option. This means instead of trying to fully parse the source file, we will just parse the templates and their params, and ignore any template content. For certain use cases, this should both make the faster and more robust.

So calling `parse` might look something like this:
```js
import parse from 'soyparser';

parse(input, {
  type: 'top'
});
```

**Comment by jbalsas** [comment]
Filed at [metal-tools-soy](https://github.com/metal/metal-tools-soy/issues/37)
